"""`gpu-bench run` — execute a single experiment from a config file."""

from __future__ import annotations

from pathlib import Path
from typing import Annotated

import typer
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

from gpu_benchlab.backends.fake import FakeBackend
from gpu_benchlab.core.backend import Backend, DeviceKind
from gpu_benchlab.core.config import ExperimentConfig, load_config
from gpu_benchlab.core.engine import BenchmarkEngine
from gpu_benchlab.core.errors import ConfigurationError
from gpu_benchlab.core.schema import BenchmarkResult, BenchmarkStatus
from gpu_benchlab.core.statistics import LatencyStatistics
from gpu_benchlab.core.storage import DEFAULT_RESULTS_DIR, ResultStore

console = Console()

EXIT_OK = 0
EXIT_BENCHMARK_NOT_OK = 1
EXIT_CONFIG_ERROR = 2

_STATUS_STYLE = {
    BenchmarkStatus.OK: "green",
    BenchmarkStatus.UNSUPPORTED: "yellow",
    BenchmarkStatus.FAILED: "red",
    BenchmarkStatus.UNAVAILABLE: "yellow",
    BenchmarkStatus.SKIPPED: "dim",
}


def build_backend(config: ExperimentConfig, *, seed: int) -> Backend:
    """Instantiate the backend named by the config.

    Raises:
        ConfigurationError: if the backend is unknown, not yet implemented, or its
            options / device / model are invalid.
    """
    name = config.backend.lower()
    if name == "fake":
        if config.backend_options:
            raise ConfigurationError(
                "backend 'fake' accepts no backend_options, got: "
                + ", ".join(sorted(config.backend_options))
            )
        return FakeBackend(seed=seed)
    if name == "pytorch":
        # Constructing the backend does not import torch; that happens in validate().
        from gpu_benchlab.backends.pytorch import PyTorchBackend

        return PyTorchBackend(config)

    known_but_unimplemented = {"onnxruntime": 4, "tensorrt": 5, "tensorrt_llm": 10}
    if name in known_but_unimplemented:
        raise ConfigurationError(
            f"Backend {config.backend!r} is not implemented yet "
            f"(planned for Phase {known_but_unimplemented[name]}). "
            "Available now: 'pytorch', and 'fake' (simulated)."
        )
    raise ConfigurationError(
        f"Unknown backend {config.backend!r}. Available now: 'pytorch', 'fake' (simulated)."
    )


def register(app: typer.Typer) -> None:
    """Attach the `run` command to the CLI app."""

    @app.command()
    def run(
        config_path: Annotated[
            Path, typer.Option("--config", "-c", help="Path to an experiment YAML file.")
        ],
        results_dir: Annotated[
            Path, typer.Option("--results-dir", help="Where to write the result.")
        ] = DEFAULT_RESULTS_DIR,
        seed: Annotated[int, typer.Option("--seed", help="Seed for the simulated backend.")] = 0,
        no_save: Annotated[
            bool, typer.Option("--no-save", help="Run without writing the result to disk.")
        ] = False,
    ) -> None:
        """Run one benchmark experiment from a configuration file."""
        try:
            config = load_config(config_path)
            backend = build_backend(config, seed=seed)
        except ConfigurationError as exc:
            console.print(f"[red]Configuration error:[/red]\n{exc}")
            raise typer.Exit(EXIT_CONFIG_ERROR) from exc

        descriptor = backend.descriptor
        if descriptor.is_simulated:
            _print_simulation_banner()
        elif descriptor.device_kind is DeviceKind.CPU:
            _print_cpu_banner()

        console.print(
            f"Running [cyan]{config.name}[/cyan] "
            f"(backend={config.backend}, device={descriptor.device}, "
            f"precision={config.precision.value}, "
            f"batch={config.batch_size}, "
            f"warmup={config.benchmark.warmup_iterations}, "
            f"iters={config.benchmark.measurement_iterations})\n"
        )

        result = BenchmarkEngine().run(backend, config)
        _render_result(result)

        if not no_save:
            directory = ResultStore(results_dir).save(result)
            console.print(f"\n[dim]Result written to {directory}[/dim]")

        raise typer.Exit(EXIT_OK if result.succeeded else EXIT_BENCHMARK_NOT_OK)


def _print_simulation_banner() -> None:
    console.print(
        Panel(
            "This run uses the [bold]simulated[/bold] backend.\n"
            "The numbers below are generated by a seeded random model. They exercise "
            "the benchmarking framework and are [bold]NOT measurements[/bold] of any "
            "GPU, model or inference runtime.",
            title="SIMULATED — NOT REAL PERFORMANCE DATA",
            border_style="yellow",
        )
    )


def _print_cpu_banner() -> None:
    console.print(
        Panel(
            "This run executes on the [bold]host CPU[/bold]. The numbers are real "
            "measurements of CPU inference.\n"
            "They are [bold]not GPU performance[/bold] and must not be compared with "
            "GPU results as a speedup.",
            title="CPU RESULT — NOT GPU PERFORMANCE",
            border_style="cyan",
        )
    )


def _render_result(result: BenchmarkResult) -> None:
    style = _STATUS_STYLE[result.status]
    console.print(f"Status: [{style}]{result.status.value}[/{style}]")
    if result.device_kind is not None:
        console.print(f"Device: [cyan]{result.device_kind.value}[/cyan] ({result.backend.device})")
    mechanism = (
        result.timing_mechanism.value if result.timing_mechanism else "none (nothing was timed)"
    )
    console.print(f"Timing mechanism: [cyan]{mechanism}[/cyan]")
    if result.secondary_timing_mechanism is not None:
        console.print(
            f"Secondary timing: [dim]{result.secondary_timing_mechanism.value} "
            "(reported separately; never the headline)[/dim]"
        )
    if result.model_info is not None:
        info = result.model_info
        sha = f", sha256 {info.weights_sha256[:16]}..." if info.weights_sha256 else ""
        console.print(
            f"Model: [cyan]{info.name}[/cyan] ({info.architecture}, "
            f"{info.parameter_count:,} params, weights {info.weights}{sha})"
        )
    if not result.measures_steady_state:
        console.print("[yellow]Warmup disabled: these samples include cold start.[/yellow]")
    console.print()

    _render_phases(result)

    if result.latency is not None:
        _render_latency(result)
        _render_throughput(result)
    if result.secondary_latency is not None and result.secondary_timing_mechanism is not None:
        sec = result.secondary_latency
        console.print(
            f"[dim]Secondary ({result.secondary_timing_mechanism.value}): "
            f"p50 {sec.p50_ms:.3f} ms, p95 {sec.p95_ms:.3f} ms, "
            f"mean {sec.mean_ms:.3f} ms[/dim]\n"
        )

    if result.errors:
        _render_errors(result)


def _render_phases(result: BenchmarkResult) -> None:
    table = Table(title="Phases", title_justify="left", box=None, pad_edge=False)
    table.add_column("Phase", style="cyan", no_wrap=True)
    table.add_column("Duration", justify="right")
    for label, value in (
        ("Model load", result.phases.model_load_ms),
        ("Engine build", result.phases.engine_build_ms),
        ("Prepare inputs", result.phases.prepare_inputs_ms),
        ("Warmup (total)", result.phases.warmup_total_ms),
        ("Measurement (total)", result.phases.measurement_total_ms),
    ):
        table.add_row(label, f"{value:.3f} ms" if value is not None else "[dim]n/a[/dim]")
    console.print(table)
    console.print()


def _render_latency(result: BenchmarkResult) -> None:
    latency = result.latency
    if latency is None:
        return

    table = Table(title="Latency", title_justify="left", box=None, pad_edge=False)
    table.add_column("Statistic", style="cyan", no_wrap=True)
    table.add_column("Value", justify="right")
    table.add_column("", style="yellow")

    rows = [
        ("samples", f"{latency.count}", ""),
        ("min", f"{latency.min_ms:.3f} ms", ""),
        ("mean", f"{latency.mean_ms:.3f} ms", ""),
        ("median", f"{latency.median_ms:.3f} ms", ""),
        ("p50", f"{latency.p50_ms:.3f} ms", _flag(latency, 50)),
        ("p90", f"{latency.p90_ms:.3f} ms", _flag(latency, 90)),
        ("p95", f"{latency.p95_ms:.3f} ms", _flag(latency, 95)),
        ("p99", f"{latency.p99_ms:.3f} ms", _flag(latency, 99)),
        ("max", f"{latency.max_ms:.3f} ms", ""),
        ("std dev", f"{latency.stddev_ms:.3f} ms", ""),
    ]
    for name, value, note in rows:
        table.add_row(name, value, note)
    console.print(table)

    if latency.low_confidence_percentiles:
        console.print(
            f"[dim]Percentiles marked 'low confidence' were computed from fewer "
            f"samples than needed for a stable estimate "
            f"({latency.count} samples). See docs/methodology.md §6.[/dim]"
        )
    console.print()


def _flag(latency: LatencyStatistics, percentile: int) -> str:
    return "low confidence" if latency.is_low_confidence(percentile) else ""


def _render_throughput(result: BenchmarkResult) -> None:
    if not result.throughput:
        return
    table = Table(title="Throughput", title_justify="left", box=None, pad_edge=False)
    table.add_column("Value", justify="right", style="cyan", no_wrap=True)
    table.add_column("Unit", no_wrap=True)
    table.add_column("Derived from", style="dim")
    for metric in result.throughput:
        table.add_row(f"{metric.value:.2f}", metric.unit.value, metric.basis)
    console.print(table)
    console.print()


def _render_errors(result: BenchmarkResult) -> None:
    table = Table(title="Errors", title_justify="left", box=None, pad_edge=False)
    table.add_column("Phase", style="cyan", no_wrap=True)
    table.add_column("Type", no_wrap=True)
    table.add_column("Message")
    for error in result.errors:
        table.add_row(error.phase or "-", error.type, error.message)
    console.print(table)
    console.print()
